import {describe,it,expect} from 'vitest';
import {empty,today} from './model';
import {purchase,produce,recordWaste,countStock,stock,inventoryValue} from './engine';
import {registerSale} from './sales';
import {deleteRecord} from './deletion';
function fixture(){let s=empty();s.suppliers=[{id:'s',name:'Proveedor',company:'',phone:'',whatsapp:'',email:'',address:'',notes:''}];s.ingredients=[{id:'q',name:'Queso',category:'',brand:'',supplierId:'s',presentation:'',packQty:'1000',packUnit:'g',min:'0',location:'',notes:'',averageCost:'0'}];s.recipes=[{id:'r',name:'Pizza',type:'producto',unit:'pieza',yield:'1',waste:'0',components:[{kind:'ingredient',ref:'q',qty:'100'}]}];s.products=[{id:'p',name:'Pizza',size:'Grande',recipeId:'r',price:'200'}];return s}
function buy(s:ReturnType<typeof empty>,price='0.1'){return purchase(s,{date:today(),supplierId:'s',ticket:'T',lines:[{ingredientId:'q',qty:'1000',unit:'g',price,expires:'2099-01-01',lotCode:'L'}],tax:'0',freight:'0',discount:'0',payment:'',notes:''})}
function sale(s:ReturnType<typeof empty>,consumeInventory=true){return registerSale(s,{items:[{productId:'p',qty:'1'}],payment:'Efectivo',received:'200',discount:'0',consumeInventory,notes:''})}
it('eliminar compra reciente restaura stock y promedio anterior sin modificar el estado original',()=>{const first=buy(fixture());const s=buy(first,'0.2');const next=deleteRecord(s,'purchase',s.purchases[1].id);expect(stock(next,'q').toString()).toBe('1000');expect(next.ingredients[0].averageCost).toBe('0.1');expect(inventoryValue(next).toString()).toBe('100');expect(next.history).toHaveLength(1);expect(stock(s,'q').toString()).toBe('2000')});
it('bloquea compras consumidas y mantiene sus datos',()=>{const s=sale(buy(fixture()));expect(()=>deleteRecord(s,'purchase',s.purchases[0].id)).toThrow('posteriores');expect(s.purchases).toHaveLength(1)});
it('eliminar venta devuelve cantidades al lote original y actualiza totales',()=>{const s=sale(buy(fixture()));const next=deleteRecord(s,'sale',s.sales[0].id);expect(stock(next,'q').toString()).toBe('1000');expect(next.sales).toHaveLength(0);expect(inventoryValue(next).toString()).toBe('100')});
it('eliminar merma restaura inventario y conserva auditoría',()=>{const s=recordWaste(buy(fixture()),'q','50','Error','');const next=deleteRecord(s,'waste',s.wastes[0].id);expect(stock(next,'q').toString()).toBe('1000');expect(next.wastes).toHaveLength(0);expect(next.audit.at(-2)?.operation).toBe('Registro eliminado · waste')});
it('producción consumida se bloquea y puede revertirse después de su consumo',()=>{let s=buy(fixture());s.recipes.push({id:'sub',name:'Salsa',type:'subreceta',unit:'g',yield:'200',waste:'0',components:[{kind:'ingredient',ref:'q',qty:'200'}]});s=produce(s,{date:today(),actor:'A',recipeId:'sub',scale:'1',finalQty:'200',waste:'0',balls:[],notes:''},{});const prepared=s.recipes[1].stockIngredientId!;s=recordWaste(s,prepared,'20','Error','');expect(()=>deleteRecord(s,'production',s.productions[0].id)).toThrow('posteriores');s=deleteRecord(s,'waste',s.wastes[0].id);s=deleteRecord(s,'production',s.productions[0].id);expect(stock(s,'q').toString()).toBe('1000');expect(stock(s,prepared).toString()).toBe('0');expect(s.productions).toHaveLength(0)});
it('revertir ajustes de conteo positivos y negativos',()=>{let s=countStock(buy(fixture()),'q','1100','Conteo');s=deleteRecord(s,'movement',s.movements.at(-1)!.id);expect(stock(s,'q').toString()).toBe('1000');s=countStock(s,'q','900','Conteo');s=deleteRecord(s,'movement',s.movements.at(-1)!.id);expect(stock(s,'q').toString()).toBe('1000')});
it('catálogos protegidos y producto eliminable conserva ticket histórico',()=>{let s=sale(buy(fixture()),false);expect(()=>deleteRecord(s,'ingredient','q')).toThrow();expect(()=>deleteRecord(s,'supplier','s')).toThrow();expect(()=>deleteRecord(s,'recipe','r')).toThrow();s=deleteRecord(s,'product','p');expect(s.products).toHaveLength(0);expect(s.sales[0].items[0].name).toBe('Pizza')});
it('no reutiliza números de ticket después de eliminar la última venta',()=>{let s=sale(buy(fixture()),false);s=deleteRecord(s,'sale',s.sales[0].id);s=sale(s,false);expect(s.sales[0].ticket).toBe('V-000002')});
it('FIFO: al revertir venta se conserva el valor financiero anterior',()=>{let s=fixture();s.settings.valuation='fifo';s=buy(s);s=buy(s,'0.2');const before=inventoryValue(s).toString();s=sale(s);s=deleteRecord(s,'sale',s.sales[0].id);expect(inventoryValue(s).toString()).toBe(before)});
