import Decimal from 'decimal.js';
import {id,now,today,type State,type Purchase,type Recipe,type Component,type Production} from './model';
Decimal.set({precision:40,rounding:Decimal.ROUND_HALF_UP});
export const D=(n:Decimal.Value)=>new Decimal(n);
export const sum=(a:Decimal.Value[])=>a.reduce<Decimal>((s,n)=>s.plus(n),D(0));
export function positive(n:string,label='Cantidad',zero=false){if(!/^\d+(\.\d+)?$/.test(n)||!D(n).isFinite()||(zero?D(n).lt(0):D(n).lte(0)))throw Error(`${label}: introduce un número ${zero?'no negativo':'mayor que cero'}.`);return D(n)}
export function convert(qty:string,unit:string,base:string){positive(qty);const map:Record<string,[string,string]>={kg:['g','1000'],g:['g','1'],L:['ml','1000'],ml:['ml','1'],pieza:['pieza','1'],min:['min','1']};if(!map[unit]||map[unit][0]!==base)throw Error('Unidades incompatibles. Define el contenido de la presentación.');return D(qty).mul(map[unit][1]).toString()}
export const stock=(s:State,ingredientId:string)=>sum(s.lots.filter(l=>l.ingredientId===ingredientId).map(l=>l.qty));
export const ingredientCost=(s:State,ref:string)=>{const i=s.ingredients.find(i=>i.id===ref);if(!i)throw Error('Insumo inexistente');return D(i.averageCost)};
export function inventoryValue(s:State){return s.settings.valuation==='average'?sum(s.ingredients.map(i=>stock(s,i.id).mul(i.averageCost))):sum(s.movements.map(m=>D(m.qty).mul(m.unitCost)))}
export function componentCost(s:State,c:Component,seen:string[]=[]):Decimal {positive(c.qty,'Cantidad de componente');if(c.kind==='ingredient')return ingredientCost(s,c.ref).mul(c.qty);if(c.kind==='equipment'){const e=s.equipment.find(e=>e.id===c.ref);if(!e)throw Error('Equipo inexistente');return positive(e.price,'Costo de energía').div(positive(e.hours,'Horas').mul(60)).mul(c.qty)}const r=s.recipes.find(r=>r.id===c.ref);if(!r)throw Error('Subreceta inexistente');return recipeCost(s,r,seen).div(useful(r)).mul(c.qty)}
export const useful=(r:Recipe)=>{const result=positive(r.yield,'Rendimiento').minus(positive(r.waste,'Merma',true));if(result.lte(0))throw Error('La merma debe ser menor que el rendimiento');return result};
export function recipeCost(s:State,r:Recipe,seen:string[]=[]):Decimal {if(seen.includes(r.id))throw Error('Las recetas no pueden contener ciclos');return sum(r.components.map(c=>componentCost(s,c,[...seen,r.id])))}
export function flatten(s:State,r:Recipe,scale:Decimal,seen:string[]=[]):Map<string,Decimal>{if(seen.includes(r.id))throw Error('Ciclo de subrecetas');const result=new Map<string,Decimal>();for(const c of r.components){if(c.kind==='ingredient')result.set(c.ref,(result.get(c.ref)||D(0)).plus(D(c.qty).mul(scale)));if(c.kind==='recipe'){const sub=s.recipes.find(x=>x.id===c.ref);if(!sub)throw Error('Subreceta inexistente');if(sub.stockIngredientId){result.set(sub.stockIngredientId,(result.get(sub.stockIngredientId)||D(0)).plus(D(c.qty).mul(scale)))}else for(const [ref,q] of flatten(s,sub,D(c.qty).mul(scale).div(useful(sub)),[...seen,r.id]))result.set(ref,(result.get(ref)||D(0)).plus(q));}}return result}
export function transact(s:State,operation:string,fn:(draft:State)=>void):State {const draft=structuredClone(s);fn(draft);draft.audit.push({id:id(),date:now(),actor:s.settings.actor,operation,before:JSON.stringify({lots:s.lots.length,movements:s.movements.length}),after:JSON.stringify({lots:draft.lots.length,movements:draft.movements.length}),reference:operation});return draft}
export function consume(s:State,ingredientId:string,qty:string,type:string,reference:string,allowExpired=false){let remaining=positive(qty);const lots=s.lots.filter(l=>l.ingredientId===ingredientId&&D(l.qty).gt(0)&&(allowExpired||!l.expires||l.expires>=today())).sort((a,b)=>(a.expires||'9999').localeCompare(b.expires||'9999')||a.entered.localeCompare(b.entered));if(sum(lots.map(l=>l.qty)).lt(remaining))throw Error(`Stock utilizable insuficiente de ${s.ingredients.find(i=>i.id===ingredientId)?.name}`);let cost=D(0);for(const lot of lots){if(remaining.eq(0))break;const take=Decimal.min(remaining,lot.qty);const financial=s.settings.valuation==='average'?ingredientCost(s,ingredientId):fifoCost(s,ingredientId,take);cost=cost.plus(financial.mul(take));lot.qty=D(lot.qty).minus(take).toString();s.movements.push({id:id(),date:now(),ingredientId,lotId:lot.id,type,qty:take.neg().toString(),unitCost:financial.toString(),physicalCost:lot.unitCost,reference,actor:s.settings.actor,notes:''});remaining=remaining.minus(take)}return cost}
function fifoCost(s:State,ref:string,quantity:Decimal){const layers=s.lots.filter(l=>l.ingredientId===ref).sort((a,b)=>a.entered.localeCompare(b.entered));let consumed=sum(s.movements.filter(m=>m.ingredientId===ref&&D(m.qty).lt(0)).map(m=>D(m.qty).abs()));let left=quantity,total=D(0);for(const l of layers){const skipped=Decimal.min(consumed,l.initialQty);consumed=consumed.minus(skipped);const available=D(l.initialQty).minus(skipped);const take=Decimal.min(left,available);total=total.plus(take.mul(l.unitCost));left=left.minus(take);if(left.eq(0))break}if(left.gt(0))throw Error('Capas FIFO insuficientes');return total.div(quantity)}
export function purchase(s:State,input:Omit<Purchase,'id'|'total'>){return transact(s,'Compra',draft=>{if(!draft.suppliers.some(x=>x.id===input.supplierId))throw Error('Selecciona un proveedor');if(!input.lines.length)throw Error('Agrega al menos una partida');const values=input.lines.map(l=>positive(l.qty).mul(positive(l.price,'Precio')));const subtotal=sum(values);const tax=positive(input.tax,'Impuestos',true),freight=positive(input.freight,'Flete',true),discount=positive(input.discount,'Descuento',true);if(discount.gt(subtotal))throw Error('Descuento superior al subtotal');const total=subtotal.plus(tax).plus(freight).minus(discount);const ref=id();input.lines.forEach((l,index)=>{const i=draft.ingredients.find(i=>i.id===l.ingredientId);if(!i)throw Error('Insumo inexistente');const qty=l.unit==='presentación'?positive(l.qty).mul(i.packQty).toString():convert(l.qty,l.unit,i.packUnit);const landed=values[index].plus(values[index].div(subtotal).mul(tax.plus(freight).minus(discount)));const unitCost=landed.div(qty);const previous=i.averageCost;const old=stock(draft,i.id);i.averageCost=old.mul(previous).plus(landed).div(old.plus(qty)).toString();const lotId=id();draft.lots.push({id:lotId,ingredientId:i.id,supplierId:input.supplierId,code:l.lotCode||ref.slice(0,8),entered:input.date,purchased:input.date,expires:l.expires,qty,initialQty:qty,unitCost:unitCost.toString(),location:i.location});draft.movements.push({id:id(),date:input.date,ingredientId:i.id,lotId,type:'Entrada por compra',qty,unitCost:unitCost.toString(),physicalCost:unitCost.toString(),reference:ref,actor:draft.settings.actor,notes:input.ticket});draft.history.push({id:id(),date:input.date,ingredientId:i.id,supplierId:input.supplierId,previous,current:i.averageCost,reference:ref});});draft.purchases.push({...input,id:ref,total:total.toString()});})}
export function produce(s:State,input:Omit<Production,'id'|'actualCost'|'theoreticalCost'|'items'>,actual:Record<string,string>){return transact(s,'Producción',draft=>{const r=draft.recipes.find(r=>r.id===input.recipeId);if(!r)throw Error('Receta inexistente');const scale=positive(input.scale);const final=positive(input.finalQty);const waste=positive(input.waste,'Merma',true);if(waste.gte(final))throw Error('Merma superior al peso final');if(input.balls.some(b=>!D(b.count).isInteger()))throw Error('La cantidad de bolas debe ser entera');if(sum(input.balls.map(b=>positive(b.grams).mul(positive(b.count)))).gt(final.minus(waste)))throw Error('Las bolas exceden la masa útil');const ref=id(),requirements=flatten(draft,r,scale);const items=[...requirements].map(([ingredientId,q])=>{const qty=actual[ingredientId]||q.toString();const cost=consume(draft,ingredientId,qty,'Salida por producción',ref);return {ingredientId,qty,cost:cost.toString()}});const energy=energyCost(draft,r,scale);draft.productions.push({...input,id:ref,items,theoreticalCost:recipeCost(s,r).mul(scale).toString(),actualCost:sum(items.map(i=>i.cost)).plus(energy).toString()});if(r.type!=='producto')receivePreparation(draft,r,final.minus(waste),sum(items.map(i=>i.cost)).plus(energy),ref,input.date);})}
function energyCost(s:State,r:Recipe,scale:Decimal):Decimal{return sum(r.components.map(c=>c.kind==='equipment'?componentCost(s,c).mul(scale):c.kind==='recipe'&&!s.recipes.find(x=>x.id===c.ref)?.stockIngredientId?energyCost(s,s.recipes.find(x=>x.id===c.ref)!,D(c.qty).mul(scale).div(useful(s.recipes.find(x=>x.id===c.ref)!))):D(0)))}
function receivePreparation(s:State,r:Recipe,qty:Decimal,cost:Decimal,reference:string,date:string){if(!r.stockIngredientId){r.stockIngredientId=id();s.ingredients.push({id:r.stockIngredientId,name:r.name+' · elaborado',category:'Elaborados',brand:'Producción interna',supplierId:'',presentation:'Preparación interna',packQty:useful(r).toString(),packUnit:r.unit,min:'0',location:'Cocina',notes:'Generado por producción',averageCost:'0'})}const ingredient=s.ingredients.find(i=>i.id===r.stockIngredientId)!;const previous=stock(s,ingredient.id);ingredient.averageCost=previous.mul(ingredient.averageCost).plus(cost).div(previous.plus(qty)).toString();const lotId=id(),unitCost=cost.div(qty).toString();s.lots.push({id:lotId,ingredientId:ingredient.id,supplierId:'',code:'PROD-'+reference.slice(0,8),entered:date.slice(0,10),purchased:date.slice(0,10),expires:'',qty:qty.toString(),initialQty:qty.toString(),unitCost,location:'Cocina'});s.movements.push({id:id(),date,ingredientId:ingredient.id,lotId,type:'Entrada por producción',qty:qty.toString(),unitCost,physicalCost:unitCost,reference,actor:s.settings.actor,notes:'Lote de preparación interna; asigna su caducidad en Inventario → Lotes'});}
export function recordWaste(s:State,ingredientId:string,qty:string,reason:string,notes:string){return transact(s,'Merma',draft=>{const ref=id();const cost=consume(draft,ingredientId,qty,'Merma',ref,true);draft.wastes.push({id:ref,date:now(),ingredientId,qty,cost:cost.toString(),reason,actor:s.settings.actor,notes})})}
export function countStock(s:State,ref:string,count:string,notes:string){return transact(s,'Conteo físico',draft=>{const value=positive(count,'Conteo',true),difference=value.minus(stock(draft,ref));if(difference.lt(0))consume(draft,ref,difference.abs().toString(),'Ajuste por conteo',notes,true);if(difference.gt(0)){const lotId=id(),unitCost=ingredientCost(draft,ref).toString();draft.lots.push({id:lotId,ingredientId:ref,supplierId:'',code:'CONTEO',entered:today(),purchased:today(),expires:'',qty:difference.toString(),initialQty:difference.toString(),unitCost,location:''});draft.movements.push({id:id(),date:now(),ingredientId:ref,lotId,type:'Ajuste por conteo',qty:difference.toString(),unitCost,physicalCost:unitCost,reference:notes,actor:s.settings.actor,notes})}})}
export function alerts(s:State){const result:{severity:string;title:string;detail:string;ref:string}[]=[];for(const i of s.ingredients){const q=stock(s,i.id);if(q.lte(i.min))result.push({severity:q.eq(0)?'critical':'warning',title:q.eq(0)?'Stock crítico':'Stock bajo',detail:`${i.name} · ${q} ${i.packUnit} / mínimo ${i.min}`,ref:i.id})}for(const l of s.lots.filter(l=>D(l.qty).gt(0)&&l.expires)){const days=Math.round((Date.parse(l.expires)-Date.parse(today()))/86400000);if(days<=s.settings.expiryDays)result.push({severity:days<0?'critical':'warning',title:days<0?'Caducado':days===0?'Caduca hoy':`Caduca en ${days} días`,detail:`${s.ingredients.find(i=>i.id===l.ingredientId)?.name} · lote ${l.code}`,ref:l.ingredientId})}for(const h of s.history){if(D(h.previous).gt(0)&&D(h.current).minus(h.previous).div(h.previous).mul(100).gte(s.settings.priceAlert)&&h.date.slice(0,10)>=new Date(Date.parse(today())-30*86400000).toISOString().slice(0,10))result.push({severity:'info',title:'Incremento de precio',detail:`${s.ingredients.find(i=>i.id===h.ingredientId)?.name} · +${D(h.current).minus(h.previous).div(h.previous).mul(100).toFixed(1)}%`,ref:h.ingredientId})}return result}





