import {describe,it,expect} from 'vitest';
import {D,convert,purchase,recipeCost,useful,consume,produce,transact,recordWaste,stock} from './engine';
import {empty,today,type State} from './model';
import {inventoryValue} from './engine';
function fixture(){const s=empty();s.suppliers=[{id:'s',name:'Proveedor',company:'',phone:'',whatsapp:'',email:'',address:'',notes:''}];s.ingredients=[{id:'q',name:'Queso',category:'Lácteos',brand:'',supplierId:'s',presentation:'2.5 kg',packQty:'2500',packUnit:'g',min:'0',location:'',notes:'',averageCost:'0'}];return s}
function buy(s:State,qty='2500',price='0.124',expires='2099-01-01'){return purchase(s,{date:today(),supplierId:'s',ticket:'T',lines:[{ingredientId:'q',qty,unit:'g',price,expires,lotCode:'L'}],tax:'0',discount:'0',freight:'0',payment:'Efectivo',notes:''})}
it('FIFO financiero permanece independiente de FEFO físico',()=>{let s=fixture();s.settings.valuation='fifo';s=buy(s,'1000','0.1','2099-02-01');s=buy(s,'1000','0.2','2099-01-01');s=transact(s,'FIFO',d=>{expect(consume(d,'q','500','Producción','P').toString()).toBe('50')});expect(s.lots[1].qty).toBe('500');expect(s.lots[0].qty).toBe('1000');expect(inventoryValue(s).toString()).toBe('250')});
it('preparaciones generan inventario y evitan descontar dos veces la materia prima',()=>{let s=buy(fixture());s.recipes=[{id:'sub',name:'Salsa',type:'subreceta',unit:'g',yield:'200',waste:'0',components:[{kind:'ingredient',ref:'q',qty:'200'}]},{id:'pizza',name:'Pizza',type:'producto',unit:'pieza',yield:'1',waste:'0',components:[{kind:'recipe',ref:'sub',qty:'100'}]}];const input={date:today(),actor:'A',scale:'1',waste:'0',balls:[],notes:''};s=produce(s,{...input,recipeId:'sub',finalQty:'200'},{});const prepared=s.recipes[0].stockIngredientId!;expect(stock(s,'q').toString()).toBe('2300');expect(stock(s,prepared).toString()).toBe('200');s=produce(s,{...input,recipeId:'pizza',finalQty:'1'},{});expect(stock(s,'q').toString()).toBe('2300');expect(stock(s,prepared).toString()).toBe('100');expect(s.productions[1].actualCost).toBe('12.4')});
describe('Motor de unidades y costos',()=>{it('convierte kg/g y L/ml y rechaza dimensiones incompatibles',()=>{expect(convert('2.5','kg','g')).toBe('2500');expect(convert('6','L','ml')).toBe('6000');expect(()=>convert('1','L','g')).toThrow();expect(()=>convert('-1','kg','g')).toThrow()});it('calcula 310 / 2500 y el queso de una pizza sin redondeo prematuro',()=>{const s=buy(fixture());expect(s.ingredients[0].averageCost).toBe('0.124');expect(D(s.ingredients[0].averageCost).mul(180).toString()).toBe('22.32')});it('promedio ponderado y flete/impuestos/descuento',()=>{let s=buy(fixture(),'1000','0.1');s=purchase(s,{date:today(),supplierId:'s',ticket:'2',lines:[{ingredientId:'q',qty:'1000',unit:'g',price:'0.2',expires:'',lotCode:'B'}],tax:'16',discount:'10',freight:'14',payment:'',notes:''});expect(s.ingredients[0].averageCost).toBe('0.16');expect(s.purchases[1].total).toBe('220')});it('subrecetas, rendimiento de masa y bolas',()=>{const s=buy(fixture());s.recipes=[{id:'masa',name:'Masa',type:'masa',unit:'g',yield:'15250',waste:'250',components:[{kind:'ingredient',ref:'q',qty:D(450).div('0.124').toString()}]},{id:'pizza',name:'Pizza',type:'producto',unit:'pieza',yield:'1',waste:'0',components:[{kind:'recipe',ref:'masa',qty:'300'}]}];expect(recipeCost(s,s.recipes[0]).toFixed(8)).toBe('450.00000000');expect(recipeCost(s,s.recipes[1]).toFixed(2)).toBe('9.00');expect(useful(s.recipes[0]).div(300).toString()).toBe('50')});it('detecta ciclos',()=>{const s=fixture();s.recipes=[{id:'a',name:'A',type:'subreceta',unit:'g',yield:'1',waste:'0',components:[{kind:'recipe',ref:'a',qty:'1'}]}];expect(()=>recipeCost(s,s.recipes[0])).toThrow('ciclos')})});
describe('Lotes, transacciones e historia',()=>{it('FEFO selecciona el lote próximo, excluye caducados',()=>{let s=buy(fixture(),'1000','0.1','2099-02-01');s=buy(s,'1000','0.2','2099-01-01');s=buy(s,'500','0.3','2000-01-01');const result=transact(s,'Consumo',d=>{consume(d,'q','1100','Producción','P')});expect(result.lots[1].qty).toBe('0');expect(result.lots[0].qty).toBe('900');expect(result.lots[2].qty).toBe('500');expect(s.lots[1].qty).toBe('1000')});it('no permite stock negativo ni commits parciales',()=>{const s=buy(fixture(),'100');expect(()=>transact(s,'Consumo',d=>{consume(d,'q','50','Producción','P');consume(d,'q','100','Producción','P')})).toThrow();expect(stock(s,'q').toString()).toBe('100');expect(s.movements).toHaveLength(1)});it('producción conserva costo histórico tras compra nueva',()=>{let s=buy(fixture());s.recipes=[{id:'r',name:'Receta',type:'subreceta',unit:'g',yield:'200',waste:'0',components:[{kind:'ingredient',ref:'q',qty:'200'}]}];s=produce(s,{date:today(),actor:'A',recipeId:'r',scale:'1',finalQty:'200',waste:'0',balls:[],notes:''},{});const original=s.productions[0].actualCost;s=buy(s,'1000','0.5');expect(s.productions[0].actualCost).toBe(original);expect(original).toBe('24.8');expect(recipeCost(s,s.recipes[0]).gt(original)).toBe(true)});it('merma y movimiento trazables',()=>{const s=recordWaste(buy(fixture()),'q','100','Daño','Prueba');expect(s.wastes[0].cost).toBe('12.4');expect(s.movements[1].qty).toBe('-100');expect(s.audit.at(-1)?.operation).toBe('Merma')});it('validación de rendimiento',()=>{expect(()=>useful({id:'r',name:'R',type:'masa',unit:'g',yield:'100',waste:'100',components:[]})).toThrow()})});
