import {id,now,type State,type Sale} from './model';
import {D,sum,positive,transact,recipeCost,useful,flatten,consume,componentCost} from './engine';
export interface SaleInput {items:{productId:string;qty:string}[];payment:Sale['payment'];received:string;discount:string;consumeInventory:boolean;notes:string}
export function registerSale(state:State,input:SaleInput):State{return transact(state,'Venta de mostrador',draft=>{
 if(!input.items.length)throw Error('Agrega al menos un producto');
 if(!['Efectivo','Tarjeta','Transferencia'].includes(input.payment))throw Error('Forma de pago inválida');
 const ref=id(),date=now();
 const items=input.items.map(line=>{const qty=positive(line.qty);if(!qty.isInteger())throw Error('La cantidad de productos debe ser entera');const product=draft.products.find(p=>p.id===line.productId);if(!product)throw Error('Producto inexistente');const recipe=draft.recipes.find(r=>r.id===product.recipeId);if(!recipe||recipe.type!=='producto'||recipe.unit!=='pieza')throw Error('La venta requiere un escandallo de producto en piezas');positive(product.price,'Precio');const scale=qty.div(useful(recipe));let cost=recipeCost(draft,recipe).mul(scale);if(input.consumeInventory){const requirements=flatten(draft,recipe,scale);cost=sum([...requirements].map(([ingredientId,q])=>consume(draft,ingredientId,q.toString(),'Salida por venta',ref)));const energy=(r:typeof recipe,multiplier:ReturnType<typeof D>):ReturnType<typeof D>=>sum(r.components.map(c=>c.kind==='equipment'?componentCost(draft,c).mul(multiplier):c.kind==='recipe'?(()=>{const sub=draft.recipes.find(x=>x.id===c.ref)!;return sub.stockIngredientId?D(0):energy(sub,D(c.qty).mul(multiplier).div(useful(sub)))})():D(0)));cost=cost.plus(energy(recipe,scale));}return {productId:product.id,name:product.name,size:product.size,qty:qty.toString(),price:product.price,cost:cost.toString()};});
 const subtotal=sum(items.map(i=>D(i.qty).mul(i.price))),discount=positive(input.discount,'Descuento',true);if(discount.gt(subtotal))throw Error('El descuento excede el subtotal');const total=subtotal.minus(discount);const received=input.payment==='Efectivo'?positive(input.received,'Efectivo recibido',true):total;if(received.lt(total))throw Error('El efectivo recibido es insuficiente');
 const sale:Sale={id:ref,ticket:'V-'+String(Math.max(0,...draft.sales.map(s=>Number(s.ticket.replace(/^V-/,''))||0),...draft.audit.filter(a=>a.operation==='Ticket de venta').map(a=>{try{return Number(JSON.parse(a.after).ticket.replace(/^V-/,''))||0}catch{return 0}}))+1).padStart(6,'0'),date,actor:draft.settings.actor,payment:input.payment,received:received.toString(),change:received.minus(total).toString(),discount:discount.toString(),subtotal:subtotal.toString(),total:total.toString(),cost:sum(items.map(i=>i.cost)).toString(),consumeInventory:input.consumeInventory,notes:input.notes,items};draft.sales.push(sale);draft.audit.push({id:id(),date,actor:draft.settings.actor,operation:'Ticket de venta',before:'',after:JSON.stringify(sale),reference:ref});
});}
