import {describe,it,expect} from 'vitest';
import {empty,today,type State} from './model';
import {purchase,stock} from './engine';
import {registerSale,type SaleInput} from './sales';
function fixture():State{let s=empty();s.suppliers=[{id:'s',name:'S',company:'',phone:'',whatsapp:'',email:'',address:'',notes:''}];s.ingredients=[{id:'q',name:'Queso',category:'Lácteos',brand:'',supplierId:'s',presentation:'kg',packQty:'1000',packUnit:'g',min:'0',location:'',notes:'',averageCost:'0'}];s.recipes=[{id:'r',name:'Pizza',type:'producto',unit:'pieza',yield:'1',waste:'0',components:[{kind:'ingredient',ref:'q',qty:'100'}]}];s.products=[{id:'p',name:'Pizza queso',size:'Grande',recipeId:'r',price:'280'}];s=purchase(s,{date:today(),supplierId:'s',ticket:'P',lines:[{ingredientId:'q',qty:'1000',unit:'g',price:'0.12',expires:'2099-01-01',lotCode:'L'}],tax:'0',discount:'0',freight:'0',payment:'',notes:''});return s}
const input:SaleInput={items:[{productId:'p',qty:'2'}],payment:'Efectivo',received:'600',discount:'10',consumeInventory:false,notes:'Para llevar'};
it('venta rápida calcula total, descuento y cambio sin alterar stock en modo control',()=>{const s=fixture(),next=registerSale(s,input),sale=next.sales[0];expect(sale.total).toBe('550');expect(sale.change).toBe('50');expect(sale.cost).toBe('24');expect(stock(next,'q').toString()).toBe('1000');expect(s.sales.length).toBe(0)});
it('venta con inventario descuenta ingredientes y conserva instantáneas',()=>{const s=registerSale(fixture(),{...input,consumeInventory:true});expect(stock(s,'q').toString()).toBe('800');expect(s.movements.at(-1)?.type).toBe('Salida por venta');expect(s.sales[0].items[0].price).toBe('280');expect(s.sales[0].ticket).toBe('V-000001')});
it('tarjeta registra importe exacto sin requerir efectivo',()=>{const s=registerSale(fixture(),{...input,payment:'Tarjeta',received:'0'});expect(s.sales[0].received).toBe('550');expect(s.sales[0].change).toBe('0')});
it('no guarda una venta ni consume parcialmente si falta efectivo o inventario',()=>{const s=fixture();expect(()=>registerSale(s,{...input,consumeInventory:true,received:'100'})).toThrow();expect(()=>registerSale(s,{...input,consumeInventory:true,items:[{productId:'p',qty:'20'}],received:'10000'})).toThrow();expect(stock(s,'q').toString()).toBe('1000');expect(s.sales.length).toBe(0)});
it('rechaza cantidades fraccionarias y descuentos superiores al subtotal',()=>{expect(()=>registerSale(fixture(),{...input,items:[{productId:'p',qty:'1.5'}]})).toThrow();expect(()=>registerSale(fixture(),{...input,discount:'1000'})).toThrow()});

