import {useState,useEffect,type ReactNode} from 'react';
import {LayoutDashboard,Package,ShoppingBag,Flame,Wheat,BookOpen,Pizza,Truck,Trash2,ChartNoAxesCombined,Bell,Settings,Menu,Plus,ArrowUpRight,Download,ClipboardList,ChevronRight,LogOut} from 'lucide-react';
import {type State,type Ingredient,type Supplier,type Recipe,type Component,type PurchaseLine,id,today,empty,now} from '../domain/model';
import {D,sum,stock,inventoryValue,recipeCost,componentCost,useful,alerts,purchase,produce,recordWaste,countStock,transact,positive,flatten} from '../domain/engine';
import {LocalRepository,validate,download,csv} from '../data/repository';
import {demo} from '../data/demo';
import {Table,Field,Modal,Badge,Metric,money,number,percentage} from './shared';
import {Forms,ProductSheet,Reports,Configuration} from './screens';
import PointOfSale from './PointOfSale';
const repo=new LocalRepository();
const navigation=[['','Dashboard',LayoutDashboard],['','Punto de venta',ShoppingBag],['OPERACIÓN','Inventario',Package],['','Compras',ShoppingBag],['','Producción',Flame],['','Amasadas',Wheat],['','Recetas',BookOpen],['CATÁLOGO','Productos',Pizza],['','Insumos',Package],['','Proveedores',Truck],['CONTROL','Mermas',Trash2],['','Costos',ChartNoAxesCombined],['','Alertas',Bell],['ANÁLISIS','Repomos':return <><div className="toolbar"><div className="tabs">{['Stock','Lotes','Kardex','Conteo','Compras sugeridas'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><button className="primary" onClick={()=>setModal('insumo')}><Plus size={16}/> Nuevo insumo</button></div>{tab==='Stock'?inventoryTable(s.ingredients):tab==='Lotes'?<Table columns={['Insumo','Lote','Cantidad','Costo / base','Entrada','Caducidad','Proveedor','Ubicación','Acción']} rows={s.lots.map(l=>[ingredientName(l.ingredientId),l.code,number(l.qty)+' '+s.ingredients.find(i=>i.id===l.ingredientId)?.packUnit,money(l.unitCost),l.entered,l.expires||'Sin fecha',supplierName(l.supplierId),l.location,<button onClick={()=>{setSelected(l.id);setModal('lote')}}>Editar lote</button>])}/>:tab==='Kardex'?<Table columns={['Fecha','Insumo','Tipo','Cantidad','Costo financiero','Lote','Responsable','Referencia']} rows={s.movements.map(m=>[m.date.slice(0,16),ingredientName(m.ingredientId),m.type,m.qty,money(D(m.qty).abs().mul(m.unitCost)),s.lots.find(l=>l.id===m.lotId)?.code||'—',m.actor,m.reference])}/>:tab==='Conteo'?<><p className="hint">El conteo crea movimientos de ajuste. Para entradas positivas se crea un lote sin caducidad: verifica y completa su fecha en una compra cuando corresponda.</p><Table columns={['Insumo','Stock sistema','Unidad','Acción']} rows={s.ingredients.map(i=>[i.name,number(stock(s,i.id)),i.packUnit,<button onClick={()=>{setSelected(i.id);setModal('conteo')}}>Registrar conteo</button>])}/></>:<Table columns={['Insumo','Stock','Mínimo','Consumo 30 días','Sugerido','Proveedor']} rows={s.ingredients.map(i=>{const consumption=sum(s.movements.filter(m=>m.ingredientId===i.id&&m.type==='Salida por producción'&&m.date.slice(0,10)>=new Date(Date.parse(today())-30*86400000).toISOString().slice(0,10)).map(m=>D(m.qty).abs()));const usable=sum(s.lots.filter(l=>l.ingredientId===i.id&&(!l.expires||l.expires>new Date(Date.parse(today())+s.settings.expiryDays*86400000).toISOString().slice(0,10))).map(l=>l.qty));const need=D(i.min).plus(consumption.div(30).mul(7)).minus(usable);return [i.name,number(stock(s,i.id)),i.min,number(consumption),number((need.gt(0)?need:D(0)))+' '+i.packUnit,supplierName(i.supplierId)]})}/>}</>;
case 'Proveedores':return <><div className="toolbar"><p>Contactos, compras y precios comparables por unidad base.</p><button className="primary" onClick={()=>setModal('proveedor')}><Plus size={16}/> Nuevo proveedor</button></div><Table columns={['Proveedor','Empresa','Teléfono','Email','Compras acumuladas','Acción']} rows={s.suppliers.map(p=>[p.name,p.company,p.phone,p.email,money(sum(s.purchases.filter(c=>c.supplierId===p.id).map(c=>c.total))),<><button onClick={()=>setSelected(p.id)}>Ver historial</button><button onClick={()=>{setSelected(p.id);setModal('editar-proveedor')}}>Editar</button></>])}/><div className="section-title"><h3>Comparación de precios</h3></div><Table columns={['Insumo','Proveedor','Último precio / base','Fecha','Mejor costo']} rows={s.ingredients.flatMap(i=>{const offers=s.suppliers.flatMap(p=>{const lot=s.lots.filter(l=>l.ingredientId===i.id&&l.supplierId===p.id).sort((a,b)=>b.entered.localeCompare(a.entered))[0];return lot?[{p,lot}]:[]});const cheapest=offers.reduce((v,o)=>(v.lt(o.lot.unitCost)?v:D(o.lot.unitCost)),D(Infinity));return offers.map(o=>[i.name,o.p.name,D(o.lot.unitCost).toFixed(6)+' / '+i.packUnit,o.lot.entered,D(o.lot.unitCost).eq(cheapest)?<Badge type="good">Mejor precio</Badge>:'—'])})}/>{selected&&<><h3>Historial · {supplierName(selected)}</h3><Table columns={['Fecha','Ticket','Total','Pago']} rows={s.purchases.filter(p=>p.supplierId===selected).map(p=>[p.date,p.ticket,money(p.total),p.payment])}/></>}</>;
case 'Compras':return <><div className="toolbar"><p>Cada entrada conserva sus lotes y su historial de costo.</p><button className="primary" onClick={()=>setModal('compra')}><Plus size={16}/> Registrar compra</button></div><Table columns={['Fecha','Ticket','Proveedor','Partidas','Total','Forma de pago','Detalle']} rows={s.purchases.map(p=>[p.date,p.ticket,supplierName(p.supplierId),String(p.lines.length),money(p.total),p.payment,<button onClick={()=>{setSelected(p.id);setModal('detalle-compra')}}>Ver compra</button>])}/></>;
case 'Recetas':case 'Amasadas':return <><div className="toolbar"><p>{page==='Amasadas'?'Rendimiento y costo por gramaje, calculados al instante.':'Preparaciones conectadas a los costos vigentes de inventario.'}</p><button className="primary" onClick={()=>setModal('receta')}><Plus size={16}/> Nueva receta</button></div><div className="recipe-selector">{s.recipes.filter(r=>page!=='Amasadas'||r.type==='masa').map(r=><button className={(selected||dough?.id)===r.id?'active':''} onClick={()=>setSelected(r.id)} key={r.id}>{r.name}<small>{r.type}</small></button>)}</div>{(()=>{const r=s.recipes.find(r=>r.id===(selected||dough?.id));if(!r)return <p className="empty">Crea una receta para empezar.</p>;const cost=recipeCost(s,r);return <div className="two-col"><section className="panel recipe-sheet"><span className="eyebrow">RICETTA DELLA CASA</span><h2>{r.name}</h2><Table columns={['Ingrediente','Cantidad','Costo']} rows={r.components.map(c=>[componentName(c),number(c.qty)+' '+componentUnit(c),money(componentCost(s,c))])}/><div className="recipe-total"><span>Costo de preparación</span><strong>{money(cost)}</strong></div><button className="secondary" onClick={()=>{setSelected(r.id);setModal('editar-receta')}}>Editar receta</button></section><section className="panel"><span className="eyebrow">RENDIMIENTO</span><div className="metrics compact"><Metric label="PESO / CANTIDAD FINAL" value={number(r.yield)+' '+r.unit}/><Metric label="MERMA PREVISTA" value={number(r.waste)+' '+r.unit}/><Metric label="RENDIMIENTO ÚTIL" value={number(useful(r))+' '+r.unit}/><Metric label="COSTO POR UNIDAD" value={'$'+cost.div(useful(r)).toFixed(6)}/></div>{r.type==='masa'&&<><h3>Cada bola, su costo</h3>{s.settings.ballSizes.map(g=><div className="yield-row" key={g}><strong>{g} g</strong><span>{number(useful(r).div(g).floor(),0)} bolas completas <small>+ {number(useful(r).mod(g))} g remanente</small></span><b>{money(cost.div(useful(r)).mul(g))}</b></div>)}<p className="hint">Rendimientos alternativos para un solo tamaño. La producción permite mezclar gramajes.</p></>}<button className="primary" onClick={()=>{setSelected(r.id);setModal('produccion')}}><Flame size={16}/> Registrar producción real</button></section></div>})()}</>;
case 'Producción':return <><div className="toolbar"><p>Consumo FEFO, ingredientes reales y costos conservados.</p><button className="primary" onClick={()=>setModal('produccion')}><Plus size={16}/> Registrar producción</button></div><Table columns={['Fecha','Receta','Responsable','Costo teórico','Costo real','Rendimiento útil','Bolas obtenidas','Detalle']} rows={s.productions.map(p=>[p.date,s.recipes.find(r=>r.id===p.recipeId)?.name||'—',p.actor,money(p.theoreticalCost),money(p.actualCost),number(D(p.finalQty).minus(p.waste)),p.balls.map(b=>`${b.count} × ${b.grams} g`).join(', ')||'—',<button onClick={()=>{setSelected(p.id);setModal('detalle-produccion')}}>Ver consumo</button>])}/></>;
case 'Productos':case 'Rentabilidad':return <><div className="toolbar"><p>Escandallos con alimentos, cocción y empaque.</p><button className="primary" onClick={()=>setModal('producto')}><Plus size={16}/> Nuevo producto / tamaño</button></div><Table columns={['Producto','Tamaño','Venta','Costo variable','Contribución','Margen','Precio objetivo','Acción']} rows={s.products.map(p=>{const cost=recipeCost(s,s.recipes.find(r=>r.id===p.recipeId)!);return [p.name,p.size,money(p.price),money(cost),money(D(p.price).minus(cost)),percentage(D(p.price).minus(cost).toString(),p.price),money(cost.div(D(s.settings.target).div(100))),<><button onClick={()=>setSelected(p.id)}>Escandallo</button><button onClick={()=>{setSelected(p.id);setModal('editar-producto')}}>Editar</button></>]})}/>{(()=>{const p=s.products.find(p=>p.id===(selected||s.products[0]?.id));return p?<ProductSheet key={p.id} state={s} productId={p.id} save={next=>run(()=>next)} />:null})()}</>;
case 'Mermas':return <><div className="toolbar"><Metric label="PÉRDIDA ACUMULADA" value={money(sum(s.wastes.map(w=>w.cost)))}/><button className="primary" onClick={()=>setModal('merma')}><Plus size={16}/> Registrar merma</button></div><Table columns={['Fecha','Insumo','Cantidad','Costo','Motivo','Responsable','Observaciones']} rows={s.wastes.map(w=>[w.date.slice(0,10),ingredientName(w.ingredientId),w.qty,money(w.cost),w.reason,w.actor,w.notes])}/></>;
case 'Costos':return <><div className="toolbar"><p>Precios históricos y costos de cocción.</p><button className="primary" onClick={()=>setModal('equipo')}><Plus size={16}/> Nuevo equipo</button></div><Table columns={['Equipo','Costo de energía','Horas efectivas','Costo / minuto','Acción']} rows={s.equipment.map(e=>[e.name,money(e.price),e.hours,'$'+D(e.price).div(D(e.hours).mul(60)).toFixed(6),<button onClick={()=>{setSelected(e.id);setModal('equipo')}}>Editar</button>])}/><div className="section-title"><h3>Historial de costos por unidad base</h3></div><Table columns={['Fecha','Insumo','Anterior','Vigente','Variación','Proveedor']} rows={s.history.map(h=>[h.date,ingredientName(h.ingredientId),'$'+D(h.previous).toFixed(6),'$'+D(h.current).toFixed(6),D(h.previous).gt(0)?percentage(D(h.current).minus(h.previous).toString(),h.previous):'Inicial',supplierName(h.supplierId)])}/></>;
case 'Alertas':return <><div className="toolbar"><p>Umbral de caducidad: {s.settings.expiryDays} días · incremento de precio: {s.settings.priceAlert}%.</p><button className="secondary" onClick={()=>go('Configuración')}>Configurar umbrales</button></div><section className="panel">{alarm.map((a,i)=><div className="alert-row" key={i}><span className={'status-dot '+a.severity}/><div><strong>{a.title}</strong><p>{a.detail}</p></div><button onClick={()=>go('Inventario')}>Consultar</button></div>)}{!alarm.length&&<p className="empty">Sin alertas activas.</p>}</section></>;
case 'Reportes':return <Reports state={s}/>;
case 'Configuración':return <Configuration state={s} save={next=>run(()=>next)} error={setError}/>;
default:return <p>Página no encontrada.</p>}}
function componentName(c:Component){return c.kind==='ingredient'?ingredientName(c.ref):c.kind==='recipe'?s!.recipes.find(r=>r.id===c.ref)?.name||'—':s!.equipment.find(e=>e.id===c.ref)?.name||'—'}
function componentUnit(c:Component){return c.kind==='ingredient'?s!.ingredients.find(i=>i.id===c.ref)?.packUnit:c.kind==='recipe'?s!.recipes.find(r=>r.id===c.ref)?.unit:'min'}
function inventoryTable(items:Ingredient[]){return <Table columns={['Insumo','Stock actual','Costo / base','Valor','Próxima caducidad','Proveedor','Estado','Acción']} rows={items.map(i=>{const q=stock(state,i.id);const exp=state.lots.filter(l=>l.ingredientId===i.id&&D(l.qty).gt(0)&&l.expires).sort((a,b)=>a.expires.localeCompare(b.expires))[0]?.expires;return [i.name,number(q)+' '+i.packUnit,'$'+D(i.averageCost).toFixed(6),money(q.mul(i.averageCost)),exp||'—',supplierName(i.supplierId),<Badge type={q.eq(0)?'critical':q.lte(i.min)?'warning':'good'}>{q.eq(0)?'Crítico':q.lte(i.min)?'Bajo':'Correcto'}</Badge>,<button onClick={()=>{setSelected(i.id);setModal('editar-insumo')}}>Editar</button>]})}/>}
return <div className="app">{drawer&&<div className="drawer-backdrop" onClick={()=>setDrawer(false)}/>}<aside className={drawer?'sidebar open':'sidebar'}><div className="brand">{s.settings.compactLogo||s.settings.logo?<img src={s.settings.compactLogo||s.settings.logo} alt={s.settings.name}/>:<div className="wordmark">{s.settings.name}</div>}<span>NAPOLI · TRADIZIONE</span><div className="tricolor"><i/><i/><i/></div></div><nav>{navigation.map(([group,label,Icon])=><div key={label}>{group&&<div className="nav-group">{group}</div>}<button onClick={()=>go(label)} className={page===label?'selected':''}><Icon size={17}/><span>{label}</span>{label==='Alertas'&&alarm.length>0&&<b>{alarm.length}</b>}</button></div>)}</nav><div className="sidebar-footer"><span className="avatar">{s.settings.actor.slice(0,2).toUpperCase()}</span><div><strong>{s.settings.actor}</strong><small>Operación local</small></div><LogOut size={16}/></div></aside><main><header className="topbar"><button className="mobile-menu" aria-label="Abrir menú" onClick={()=>setDrawer(true)}><Menu size={22}/></button><span>CONTROL DE OPERACIÓN <ChevronRight size={13}/> <b>{page}</b></span><div><span className="local-badge">LOCAL · {s.ingredients.some(i=>i.demo)?'DEMO':'DATOS PROPIOS'}</span><button aria-label="Ver alertas" onClick={()=>go('Alertas')}><Bell size={19}/>{alarm.length>0&&<i/>}</button></div></header><div className="page"><div className="page-heading"><div><span className="eyebrow">{s.settings.name.toUpperCase()}</span><h1>{page==='Dashboard'?'Control de operación':page}</h1></div><span className="date">{new Intl.DateTimeFormat('es-MX',{dateStyle:'long',timeZone:'America/Hermosillo'}).format(new Date())}</span></div>{content()}<footer>Hecho para la cocina. Pensado para los números. <span>MXN · Español · Datos guardados en este navegador</span></footer></div></main>{message&&<div className="toast" role="status">✓ {message}</div>}{error&&<div className="error-toast" role="alert">{error}<button onClick={()=>setError('')}>Cerrar</button></div>}{modal&&<Modal title={{insumo:'Nuevo insumo','editar-insumo':'Editar insumo',proveedor:'Nuevo proveedor',compra:'Registrar compra',receta:'Nueva receta','editar-receta':'Editar receta',produccion:'Producción real',producto:'Nuevo producto',merma:'Registrar merma',conteo:'Conteo físico',equipo:'Costo de cocción','detalle-compra':'Detalle de compra','detalle-produccion':'Consumo histórico'}[modal]||modal} close={()=>setModal('')}><Forms kind={modal} state={s} selected={selected} submit={fn=>run(fn)} /></Modal>}</div>}






