import {useState,type ReactNode} from 'react';
import {Search,ArrowUpDown,X,ChevronLeft,ChevronRight} from 'lucide-react';
import {D} from '../domain/engine';
export const money=(n:string|number|{toString():string})=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n.toString()));
export const number=(n:string|number|{toString():string},digits=2)=>new Intl.NumberFormat('es-MX',{maximumFractionDigits:digits}).format(Number(n.toString()));
export function Table({columns,rows}:{columns:string[];rows:(string|ReactNode)[][]}){const [query,setQuery]=useState(''),[page,setPage]=useState(0),[sort,setSort]=useState(0),[desc,setDesc]=useState(false);const filtered=rows.filter(r=>r.some(c=>typeof c==='string'&&c.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>{const x=typeof a[sort]==='string'?a[sort] as string:'',y=typeof b[sort]==='string'?b[sort] as string:'';return x.localeCompare(y,'es',{numeric:true})*(desc?-1:1)});const pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages-1);return <div className="table-panel"><div className="table-tools"><label className="search"><Search size={16}/><input aria-label="Buscar en tabla" placeholder="Buscar en esta lista…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label><span>{filtered.length} registros</span></div><div className="table-scroll"><table><thead><tr>{columns.map((c,i)=><th key={c}><button onClick={()=>{setSort(i);setDesc(sort===i?!desc:false)}}>{c}<ArrowUpDown size={11}/></button></th>)}</tr></thead><tbody>{filtered.slice(current*10,current*10+10).map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} data-label={columns[j]}>{c}</td>)}</tr>)}</tbody></table>{!filtered.length&&<div className="empty">No hay registros para mostrar.</div>}</div><div className="pagination"><span>Página {current+1} de {pages}</span><button aria-label="Página anterior" disabled={current===0} onClick={()=>setPage(current-1)}><ChevronLeft size={16}/></button><button aria-label="Página siguiente" disabled={current===pages-1} onClick={()=>setPage(current+1)}><ChevronRight size={16}/></button></div></div>}
export function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
export function Modal({title,children,close}:{title:string;children:ReactNode;close:()=>void}){return <div className="overlay" onClick={e=>{if(e.target===e.currentTarget)close()}}><section role="dialog" aria-modal="true" aria-label={title} className="modal"><header><h2>{title}</h2><button aria-label="Cerrar" onClick={close}><X size={20}/></button></header>{children}</section></div>}
export function Badge({children,type='info'}:{children:ReactNode;type?:string}){return <span className={'badge '+type}><i/>{children}</span>}
export function Metric({label,value,note}:{label:string;value:string;note?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
export const percentage=(a:string,b:string)=>D(b).gt(0)?D(a).div(b).mul(100).toFixed(2)+'%':'—';
